"""Add image_url to recipes

Revision ID: f84be72f96f2
Revises: 0001
Create Date: 2026-04-21 12:35:24.519780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f84be72f96f2'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'image_url')
    # ### end Alembic commands ###
